name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install NPM dependencies
      uses: bahmutov/npm-install@v1.7.4

    - name: Run ESLint
      run: |
        npx eslint src/
